# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelAuthChangePasswordInterface")

model_instance <- OrgSagebionetworksRepoModelAuthChangePasswordInterface$new()

test_that("newPassword", {
  # tests for the property `newPassword` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`newPassword`, "EXPECTED_RESULT")
})

test_that("concreteType", {
  # tests for the property `concreteType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("passwordChangeToken", {
  # tests for the property `passwordChangeToken` (OrgSagebionetworksRepoModelAuthPasswordResetSignedToken)

  # uncomment below to test the property
  #expect_equal(model.instance$`passwordChangeToken`, "EXPECTED_RESULT")
})

test_that("username", {
  # tests for the property `username` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`username`, "EXPECTED_RESULT")
})

test_that("currentPassword", {
  # tests for the property `currentPassword` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`currentPassword`, "EXPECTED_RESULT")
})

test_that("authenticationReceipt", {
  # tests for the property `authenticationReceipt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`authenticationReceipt`, "EXPECTED_RESULT")
})

test_that("userId", {
  # tests for the property `userId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`userId`, "EXPECTED_RESULT")
})

test_that("twoFaToken", {
  # tests for the property `twoFaToken` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`twoFaToken`, "EXPECTED_RESULT")
})

test_that("otpCode", {
  # tests for the property `otpCode` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`otpCode`, "EXPECTED_RESULT")
})

test_that("otpType", {
  # tests for the property `otpType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`otpType`, "EXPECTED_RESULT")
})
