# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DrsServicesApi")

api_instance <- DrsServicesApi$new()

test_that("getGa4ghDrsV1ObjectsObjectId", {
  # tests for getGa4ghDrsV1ObjectsObjectId
  # base path: https://repo-prod.prod.sagebase.org
  # @param object_id character 
  # @param expand character 
  # @return [OrgSagebionetworksRepoModelDrsDrsObject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getGa4ghDrsV1ObjectsObjectIdAccessAccessId", {
  # tests for getGa4ghDrsV1ObjectsObjectIdAccessAccessId
  # base path: https://repo-prod.prod.sagebase.org
  # @param object_id character 
  # @param access_id character 
  # @return [OrgSagebionetworksRepoModelDrsAccessUrl]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getGa4ghDrsV1ServiceInfo", {
  # tests for getGa4ghDrsV1ServiceInfo
  # base path: https://repo-prod.prod.sagebase.org
  # @return [OrgSagebionetworksRepoModelDrsServiceInformation]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
