# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JSONSchemaServicesApi")

api_instance <- JSONSchemaServicesApi$new()

test_that("deleteRepoV1SchemaOrganizationId", {
  # tests for deleteRepoV1SchemaOrganizationId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The numeric identifier of the organization.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("deleteRepoV1SchemaTypeRegisteredId", {
  # tests for deleteRepoV1SchemaTypeRegisteredId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The relative $id of the schema to delete.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1SchemaOrganization", {
  # tests for getRepoV1SchemaOrganization
  # base path: https://repo-prod.prod.sagebase.org
  # @param name character The name of the Organization to lookup.
  # @return [OrgSagebionetworksRepoModelSchemaOrganization]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1SchemaOrganizationIdAcl", {
  # tests for getRepoV1SchemaOrganizationIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The numeric identifier of the organization.
  # @return [OrgSagebionetworksRepoModelAccessControlList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1SchemaTypeCreateAsyncGetAsyncToken", {
  # tests for getRepoV1SchemaTypeCreateAsyncGetAsyncToken
  # base path: https://repo-prod.prod.sagebase.org
  # @param async_token character Forward the token returned when the job was started.
  # @return [OrgSagebionetworksRepoModelSchemaCreateSchemaResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1SchemaTypeRegisteredId", {
  # tests for getRepoV1SchemaTypeRegisteredId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The relative $id of the JSON schema to get.
  # @return [OrgSagebionetworksRepoModelSchemaJsonSchema]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1SchemaTypeValidationAsyncGetAsyncToken", {
  # tests for getRepoV1SchemaTypeValidationAsyncGetAsyncToken
  # base path: https://repo-prod.prod.sagebase.org
  # @param async_token character Forward the token returned when the job was started.
  # @return [OrgSagebionetworksRepoModelSchemaGetValidationSchemaResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1SchemaList", {
  # tests for postRepoV1SchemaList
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_schema_list_json_schema_info_request OrgSagebionetworksRepoModelSchemaListJsonSchemaInfoRequest 
  # @return [OrgSagebionetworksRepoModelSchemaListJsonSchemaInfoResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1SchemaOrganization", {
  # tests for postRepoV1SchemaOrganization
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_schema_create_organization_request OrgSagebionetworksRepoModelSchemaCreateOrganizationRequest 
  # @return [OrgSagebionetworksRepoModelSchemaOrganization]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1SchemaOrganizationList", {
  # tests for postRepoV1SchemaOrganizationList
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_schema_list_organizations_request OrgSagebionetworksRepoModelSchemaListOrganizationsRequest 
  # @return [OrgSagebionetworksRepoModelSchemaListOrganizationsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1SchemaTypeCreateAsyncStart", {
  # tests for postRepoV1SchemaTypeCreateAsyncStart
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_schema_create_schema_request OrgSagebionetworksRepoModelSchemaCreateSchemaRequest 
  # @return [OrgSagebionetworksRepoModelAsynchAsyncJobId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1SchemaTypeValidationAsyncStart", {
  # tests for postRepoV1SchemaTypeValidationAsyncStart
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_schema_get_validation_schema_request OrgSagebionetworksRepoModelSchemaGetValidationSchemaRequest 
  # @return [OrgSagebionetworksRepoModelAsynchAsyncJobId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1SchemaVersionList", {
  # tests for postRepoV1SchemaVersionList
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_schema_list_json_schema_version_info_request OrgSagebionetworksRepoModelSchemaListJsonSchemaVersionInfoRequest 
  # @return [OrgSagebionetworksRepoModelSchemaListJsonSchemaVersionInfoResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1SchemaOrganizationIdAcl", {
  # tests for putRepoV1SchemaOrganizationIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The numeric identifier of the organization.
  # @param org_sagebionetworks_repo_model_access_control_list OrgSagebionetworksRepoModelAccessControlList 
  # @return [OrgSagebionetworksRepoModelAccessControlList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
