# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FileServicesApi")

api_instance <- FileServicesApi$new()

test_that("deleteFileV1DownloadList", {
  # tests for deleteFileV1DownloadList
  # base path: https://repo-prod.prod.sagebase.org
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("deleteFileV1FileHandleHandleId", {
  # tests for deleteFileV1FileHandleHandleId
  # base path: https://repo-prod.prod.sagebase.org
  # @param handle_id character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("deleteFileV1FileHandleHandleIdFilepreview", {
  # tests for deleteFileV1FileHandleHandleIdFilepreview
  # base path: https://repo-prod.prod.sagebase.org
  # @param handle_id character The ID of the FileHandle whose preview should be cleared.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getFileV1DownloadList", {
  # tests for getFileV1DownloadList
  # base path: https://repo-prod.prod.sagebase.org
  # @return [OrgSagebionetworksRepoModelFileDownloadList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getFileV1DownloadListAddAsyncGetAsyncToken", {
  # tests for getFileV1DownloadListAddAsyncGetAsyncToken
  # base path: https://repo-prod.prod.sagebase.org
  # @param async_token character 
  # @return [OrgSagebionetworksRepoModelFileAddFileToDownloadListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getFileV1DownloadOrderOrderId", {
  # tests for getFileV1DownloadOrderOrderId
  # base path: https://repo-prod.prod.sagebase.org
  # @param order_id character The ID of the download order to fetch.
  # @return [OrgSagebionetworksRepoModelFileDownloadOrder]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getFileV1EntityIdUploadDestination", {
  # tests for getFileV1EntityIdUploadDestination
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @return [OrgSagebionetworksRepoModelFileUploadDestination]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getFileV1EntityIdUploadDestinationLocations", {
  # tests for getFileV1EntityIdUploadDestinationLocations
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @return [ListWrapperOfUploadDestinationLocation]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getFileV1EntityIdUploadDestinationStorageLocationId", {
  # tests for getFileV1EntityIdUploadDestinationStorageLocationId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @param storage_location_id numeric 
  # @return [OrgSagebionetworksRepoModelFileUploadDestination]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getFileV1FileBulkAsyncGetAsyncToken", {
  # tests for getFileV1FileBulkAsyncGetAsyncToken
  # base path: https://repo-prod.prod.sagebase.org
  # @param async_token character 
  # @return [OrgSagebionetworksRepoModelFileBulkFileDownloadResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getFileV1FileHandleHandleId", {
  # tests for getFileV1FileHandleHandleId
  # base path: https://repo-prod.prod.sagebase.org
  # @param handle_id character The ID of the FileHandle to fetch.
  # @return [OrgSagebionetworksRepoModelFileFileHandle]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getFileV1FileHandleHandleIdUrl", {
  # tests for getFileV1FileHandleHandleIdUrl
  # base path: https://repo-prod.prod.sagebase.org
  # @param handle_id character 
  # @param redirect character When set to false, the URL will be returned as text/plain             instead of redirecting. (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getFileV1FileHandleRestoreAsyncGetAsyncToken", {
  # tests for getFileV1FileHandleRestoreAsyncGetAsyncToken
  # base path: https://repo-prod.prod.sagebase.org
  # @param async_token character 
  # @return [OrgSagebionetworksRepoModelFileFileHandleRestoreResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getFileV1FileId", {
  # tests for getFileV1FileId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character the ID of the file handle to be downloaded
  # @param file_associate_type OrgSagebionetworksRepoModelFileFileHandleAssociateType the type of object with which the file is associated
  # @param file_associate_id character the ID fo the object with which the file is associated
  # @param redirect character When set to false, the URL will be returned as text/plain             instead of redirecting. (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1DownloadListAdd", {
  # tests for postFileV1DownloadListAdd
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_file_file_handle_association_list OrgSagebionetworksRepoModelFileFileHandleAssociationList 
  # @return [OrgSagebionetworksRepoModelFileDownloadList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1DownloadListAddAsyncStart", {
  # tests for postFileV1DownloadListAddAsyncStart
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_file_add_file_to_download_list_request OrgSagebionetworksRepoModelFileAddFileToDownloadListRequest 
  # @return [OrgSagebionetworksRepoModelAsynchAsyncJobId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1DownloadListRemove", {
  # tests for postFileV1DownloadListRemove
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_file_file_handle_association_list OrgSagebionetworksRepoModelFileFileHandleAssociationList 
  # @return [OrgSagebionetworksRepoModelFileDownloadList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1DownloadOrder", {
  # tests for postFileV1DownloadOrder
  # base path: https://repo-prod.prod.sagebase.org
  # @param zip_file_name character The name to given to the resulting zip file.
  # @return [OrgSagebionetworksRepoModelFileDownloadOrder]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1DownloadOrderHistory", {
  # tests for postFileV1DownloadOrderHistory
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_file_download_order_summary_request OrgSagebionetworksRepoModelFileDownloadOrderSummaryRequest 
  # @return [OrgSagebionetworksRepoModelFileDownloadOrderSummaryResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1ExternalFileHandle", {
  # tests for postFileV1ExternalFileHandle
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_file_external_file_handle_interface OrgSagebionetworksRepoModelFileExternalFileHandleInterface 
  # @return [OrgSagebionetworksRepoModelFileExternalFileHandleInterface]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1ExternalFileHandleGoogleCloud", {
  # tests for postFileV1ExternalFileHandleGoogleCloud
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_file_google_cloud_file_handle OrgSagebionetworksRepoModelFileGoogleCloudFileHandle 
  # @return [OrgSagebionetworksRepoModelFileGoogleCloudFileHandle]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1ExternalFileHandleS3", {
  # tests for postFileV1ExternalFileHandleS3
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_file_s3_file_handle OrgSagebionetworksRepoModelFileS3FileHandle 
  # @return [OrgSagebionetworksRepoModelFileS3FileHandle]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1FileBulkAsyncStart", {
  # tests for postFileV1FileBulkAsyncStart
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_file_bulk_file_download_request OrgSagebionetworksRepoModelFileBulkFileDownloadRequest 
  # @return [OrgSagebionetworksRepoModelAsynchAsyncJobId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1FileHandleBatch", {
  # tests for postFileV1FileHandleBatch
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_file_batch_file_request OrgSagebionetworksRepoModelFileBatchFileRequest 
  # @return [OrgSagebionetworksRepoModelFileBatchFileResult]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1FileHandleHandleIdToCopyFromCopy", {
  # tests for postFileV1FileHandleHandleIdToCopyFromCopy
  # base path: https://repo-prod.prod.sagebase.org
  # @param handle_id_to_copy_from character the file handle it from which to duplicate the data
  # @param org_sagebionetworks_repo_model_file_s3_file_handle OrgSagebionetworksRepoModelFileS3FileHandle 
  # @return [OrgSagebionetworksRepoModelFileS3FileHandle]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1FileHandleRestoreAsyncStart", {
  # tests for postFileV1FileHandleRestoreAsyncStart
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_file_file_handle_restore_request OrgSagebionetworksRepoModelFileFileHandleRestoreRequest 
  # @return [OrgSagebionetworksRepoModelAsynchAsyncJobId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1FileMultipart", {
  # tests for postFileV1FileMultipart
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_file_multipart_request OrgSagebionetworksRepoModelFileMultipartRequest 
  # @param force_restart character Optional parameter. When 'forceRestart=true' is included, any             upload state for the given file will be cleared and a new             upload will be started. (optional)
  # @return [OrgSagebionetworksRepoModelFileMultipartUploadStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1FileMultipartUploadIdPresignedUrlBatch", {
  # tests for postFileV1FileMultipartUploadIdPresignedUrlBatch
  # base path: https://repo-prod.prod.sagebase.org
  # @param upload_id character The unique identifier of the file upload.
  # @param org_sagebionetworks_repo_model_file_batch_presigned_upload_url_request OrgSagebionetworksRepoModelFileBatchPresignedUploadUrlRequest 
  # @return [OrgSagebionetworksRepoModelFileBatchPresignedUploadUrlResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postFileV1FilehandlesCopy", {
  # tests for postFileV1FilehandlesCopy
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_file_batch_file_handle_copy_request OrgSagebionetworksRepoModelFileBatchFileHandleCopyRequest 
  # @return [OrgSagebionetworksRepoModelFileBatchFileHandleCopyResult]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putFileV1FileMultipartUploadIdAddPartNumber", {
  # tests for putFileV1FileMultipartUploadIdAddPartNumber
  # base path: https://repo-prod.prod.sagebase.org
  # @param upload_id character The unique identifier of the file upload.
  # @param part_number integer The part number to add. Must be a number between 1 and 10,000.
  # @param part_md5_hex character The MD5 of the uploaded part represented as a hexadecimal             string. If the provided MD5 does not match the MD5 of the             uploaded part, the add will fail.
  # @return [OrgSagebionetworksRepoModelFileAddPartResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putFileV1FileMultipartUploadIdComplete", {
  # tests for putFileV1FileMultipartUploadIdComplete
  # base path: https://repo-prod.prod.sagebase.org
  # @param upload_id character The unique identifier of the file upload.
  # @return [OrgSagebionetworksRepoModelFileMultipartUploadStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
