# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AuthenticationServices2FAApi")

api_instance <- AuthenticationServices2FAApi$new()

test_that("deleteAuthV12fa", {
  # tests for deleteAuthV12fa
  # base path: https://repo-prod.prod.sagebase.org
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getAuthV12fa", {
  # tests for getAuthV12fa
  # base path: https://repo-prod.prod.sagebase.org
  # @return [OrgSagebionetworksRepoModelAuthTwoFactorAuthStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postAuthV12fa", {
  # tests for postAuthV12fa
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_auth_totp_secret_activation_request OrgSagebionetworksRepoModelAuthTotpSecretActivationRequest 
  # @return [OrgSagebionetworksRepoModelAuthTwoFactorAuthStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postAuthV12faEnroll", {
  # tests for postAuthV12faEnroll
  # base path: https://repo-prod.prod.sagebase.org
  # @return [OrgSagebionetworksRepoModelAuthTotpSecret]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postAuthV12faRecoveryCodes", {
  # tests for postAuthV12faRecoveryCodes
  # base path: https://repo-prod.prod.sagebase.org
  # @return [OrgSagebionetworksRepoModelAuthTwoFactorAuthRecoveryCodes]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postAuthV12faToken", {
  # tests for postAuthV12faToken
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_auth_two_factor_auth_login_request OrgSagebionetworksRepoModelAuthTwoFactorAuthLoginRequest 
  # @return [OrgSagebionetworksRepoModelAuthLoginResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
