# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EntityServicesApi")

api_instance <- EntityServicesApi$new()

test_that("deleteRepoV1EntityId", {
  # tests for deleteRepoV1EntityId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to delete.
  # @param skip_trash_can character If true the entity will be flag for priority purge and                      deleted as soon as possible (optional)
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("deleteRepoV1EntityIdAcl", {
  # tests for deleteRepoV1EntityIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity that should have its ACL deleted.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("deleteRepoV1EntityIdGeneratedBy", {
  # tests for deleteRepoV1EntityIdGeneratedBy
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character - The ID of the activity to fetch.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("deleteRepoV1EntityIdSchemaBinding", {
  # tests for deleteRepoV1EntityIdSchemaBinding
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("deleteRepoV1EntityIdVersionVersionNumber", {
  # tests for deleteRepoV1EntityIdVersionVersionNumber
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity
  # @param version_number numeric The version number of the Entity to delete.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityAliasAlias", {
  # tests for getRepoV1EntityAliasAlias
  # base path: https://repo-prod.prod.sagebase.org
  # @param alias character 
  # @return [OrgSagebionetworksRepoModelEntityId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityDockerRepoId", {
  # tests for getRepoV1EntityDockerRepoId
  # base path: https://repo-prod.prod.sagebase.org
  # @param repository_name character The name of a managed docker repository
  # @return [OrgSagebionetworksRepoModelEntityId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityId", {
  # tests for getRepoV1EntityId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the entity to fetch.
  # @return [OrgSagebionetworksRepoModelEntity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdAccess", {
  # tests for getRepoV1EntityIdAccess
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to check the permission on.
  # @param access_type character The permission to check. Must be from:                    ,<a href=\"${org.sagebionetworks.repo.model.ACCESS_TYPE}\">,ACCESS_TYPE,</a>
  # @return [character]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdAcl", {
  # tests for getRepoV1EntityIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to get the ACL for.
  # @return [OrgSagebionetworksRepoModelAccessControlList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdActionsDownload", {
  # tests for getRepoV1EntityIdActionsDownload
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @return [OrgSagebionetworksRepoModelDownloadActionRequiredList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdAnnotations2", {
  # tests for getRepoV1EntityIdAnnotations2
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character - The id of the entity to update.
  # @param include_derived character - When set to 'true', the derived annotations will be                        included in the results. Default value 'false'.
  # @return [OrgSagebionetworksRepoModelAnnotationV2Annotations]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdBenefactor", {
  # tests for getRepoV1EntityIdBenefactor
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the entity to get the benefactor for.
  # @return [OrgSagebionetworksRepoModelEntityHeader]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdDerivedKeys", {
  # tests for getRepoV1EntityIdDerivedKeys
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @return [OrgSagebionetworksRepoModelAnnotationV2Keys]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdFilehandles", {
  # tests for getRepoV1EntityIdFilehandles
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the FileEntity to get.
  # @return [OrgSagebionetworksRepoModelFileFileHandleResults]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdFilepreview", {
  # tests for getRepoV1EntityIdFilepreview
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the FileEntity to get.
  # @param redirect character When set to false, the URL will be returned as text/plain                  instead of redirecting. (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdGeneratedBy", {
  # tests for getRepoV1EntityIdGeneratedBy
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the activity to fetch.
  # @return [OrgSagebionetworksRepoModelProvenanceActivity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdJson", {
  # tests for getRepoV1EntityIdJson
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @param include_derived_annotations character true if annotations that are derived from a                                   bound schema should be included in the                                   response, false otherwise (default false)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdPath", {
  # tests for getRepoV1EntityIdPath
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to get the full path for.
  # @return [OrgSagebionetworksRepoModelEntityPath]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdPermissions", {
  # tests for getRepoV1EntityIdPermissions
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to get permissions for.
  # @return [OrgSagebionetworksRepoModelAuthUserEntityPermissions]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdSchemaBinding", {
  # tests for getRepoV1EntityIdSchemaBinding
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the entity.
  # @return [OrgSagebionetworksRepoModelSchemaJsonSchemaObjectBinding]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdSchemaValidation", {
  # tests for getRepoV1EntityIdSchemaValidation
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity.
  # @return [OrgSagebionetworksRepoModelSchemaValidationResults]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdSchemaValidationStatistics", {
  # tests for getRepoV1EntityIdSchemaValidationStatistics
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the container Entity.
  # @return [OrgSagebionetworksRepoModelSchemaValidationSummaryStatistics]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdSts", {
  # tests for getRepoV1EntityIdSts
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the entity to get credentials. This must be a                    folder with an STS-enabled storage location.
  # @param permission OrgSagebionetworksRepoModelStsStsPermission Read-only or read-write permissions. See ,<a href=\"${org.sagebionetworks.repo.model.sts.StsPermission}\">,StsPermission,</a>,.
  # @return [OrgSagebionetworksRepoModelStsStsCredentials]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdType", {
  # tests for getRepoV1EntityIdType
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to get the EntityHeader for.
  # @return [OrgSagebionetworksRepoModelEntityHeader]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdVersion", {
  # tests for getRepoV1EntityIdVersion
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to get all versions for.
  # @param offset integer The offset index determines where this page will start                      from. When null it will default to 0. (optional)
  # @param limit integer Limits the number of entities that will be fetched for                      this page. When null it will default to 10. (optional)
  # @return [PaginatedResultsOfVersionInfo]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdVersionVersionNumber", {
  # tests for getRepoV1EntityIdVersionVersionNumber
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity.
  # @param version_number numeric The version number of the Entity to get.
  # @return [OrgSagebionetworksRepoModelEntity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdVersionVersionNumberAnnotations2", {
  # tests for getRepoV1EntityIdVersionVersionNumberAnnotations2
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity.
  # @param version_number numeric The version number of the Entity.
  # @return [OrgSagebionetworksRepoModelAnnotationV2Annotations]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdVersionVersionNumberFilehandles", {
  # tests for getRepoV1EntityIdVersionVersionNumberFilehandles
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the FileEntity to get.
  # @param version_number numeric The version number of the FileEntity to get
  # @return [OrgSagebionetworksRepoModelFileFileHandleResults]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdVersionVersionNumberFilepreview", {
  # tests for getRepoV1EntityIdVersionVersionNumberFilepreview
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the FileEntity to get.
  # @param version_number numeric The version number of the FileEntity to get.
  # @param redirect character When set to false, the URL will be returned as                       text/plain instead of redirecting. (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdVersionVersionNumberGeneratedBy", {
  # tests for getRepoV1EntityIdVersionVersionNumberGeneratedBy
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the entity to fetch.
  # @param version_number numeric the version of the entity
  # @return [OrgSagebionetworksRepoModelProvenanceActivity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdVersionVersionNumberJson", {
  # tests for getRepoV1EntityIdVersionVersionNumberJson
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @param version_number numeric 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityMd5Md5", {
  # tests for getRepoV1EntityMd5Md5
  # base path: https://repo-prod.prod.sagebase.org
  # @param md5 character 
  # @return [PaginatedResultsOfEntityHeader]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityType", {
  # tests for getRepoV1EntityType
  # base path: https://repo-prod.prod.sagebase.org
  # @param batch character A comma separated list of Entity IDs to get EntityHeaders                      for.
  # @return [PaginatedResultsOfEntityHeader]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1RESTResources", {
  # tests for getRepoV1RESTResources
  # base path: https://repo-prod.prod.sagebase.org
  # @return [OrgSagebionetworksRepoModelRestResourceList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1RESTResourcesEffectiveSchema", {
  # tests for getRepoV1RESTResourcesEffectiveSchema
  # base path: https://repo-prod.prod.sagebase.org
  # @param resource_id character The full name of the resource (see                    ,<a href=\"${GET.REST.resources}\">,GET /REST/resources,</a>, for                    the full list of names).
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1RESTResourcesSchema", {
  # tests for getRepoV1RESTResourcesSchema
  # base path: https://repo-prod.prod.sagebase.org
  # @param resource_id character The full name of the resource (see                    ,<a href=\"${GET.REST.resources}\">,GET /REST/resources,</a>, for                    the full list of names).
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1Entity", {
  # tests for postRepoV1Entity
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_entity OrgSagebionetworksRepoModelEntity 
  # @param generated_by character To track the Provenance of an Entity create, include the                     ID of the ,<a href=\"${org.sagebionetworks.repo.model.provenance.Activity}\">,Activity,</a>, that was created to track the change. For                     more information see: ,<a href=\"${POST.activity}\">,POST                     /activity,</a>,. You must be the creator of the ,<a href=\"${org.sagebionetworks.repo.model.provenance.Activity}\">,Activity,</a>, used here. (optional)
  # @return [OrgSagebionetworksRepoModelEntity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1EntityChild", {
  # tests for postRepoV1EntityChild
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_entity_entity_lookup_request OrgSagebionetworksRepoModelEntityEntityLookupRequest 
  # @return [OrgSagebionetworksRepoModelEntityId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1EntityChildren", {
  # tests for postRepoV1EntityChildren
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_entity_children_request OrgSagebionetworksRepoModelEntityChildrenRequest 
  # @return [OrgSagebionetworksRepoModelEntityChildrenResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1EntityHeader", {
  # tests for postRepoV1EntityHeader
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_request_reference_list OrgSagebionetworksRepoModelRequestReferenceList 
  # @return [PaginatedResultsOfEntityHeader]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1EntityIdAcl", {
  # tests for postRepoV1EntityIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to create an ACL for.
  # @param org_sagebionetworks_repo_model_access_control_list OrgSagebionetworksRepoModelAccessControlList 
  # @return [OrgSagebionetworksRepoModelAccessControlList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1EntityIdSchemaValidationInvalid", {
  # tests for postRepoV1EntityIdSchemaValidationInvalid
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the container Entity.
  # @param org_sagebionetworks_repo_model_schema_list_validation_results_request OrgSagebionetworksRepoModelSchemaListValidationResultsRequest 
  # @return [OrgSagebionetworksRepoModelSchemaListValidationResultsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1EntityId", {
  # tests for putRepoV1EntityId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the entity to update. This ID must match the ID                     of the passed Entity in the request body.
  # @param org_sagebionetworks_repo_model_entity OrgSagebionetworksRepoModelEntity 
  # @param generated_by character To track the Provenance of an Entity update, include the                     ID of the ,<a href=\"${org.sagebionetworks.repo.model.provenance.Activity}\">,Activity,</a>, that was created to track the change. For                     more information see: ,<a href=\"${POST.activity}\">,POST                     /activity,</a>,. You must be the creator of the ,<a href=\"${org.sagebionetworks.repo.model.provenance.Activity}\">,Activity,</a>, used here. (optional)
  # @param new_version character To force the creation of a new version for a ,<a href=\"${org.sagebionetworks.repo.model.VersionableEntity}\">,versionable,</a>,                     entity such as a ,<a href=\"${org.sagebionetworks.repo.model.FileEntity}\">,FileEntity,</a>,,                     include this optional parameter with a value set to true                     (i.e. newVersion=true). This parameter is ignored for                     entities of type ,<a href=\"${org.sagebionetworks.repo.model.table.Table}\">,Table,</a>,                     (See ,<a href=\"${POST.entity.id.table.snapshot}\">,POST                     /entity/{id}/table/snapshot,</a>, instead) (optional)
  # @return [OrgSagebionetworksRepoModelEntity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1EntityIdAcl", {
  # tests for putRepoV1EntityIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to create an ACL for.
  # @param org_sagebionetworks_repo_model_access_control_list OrgSagebionetworksRepoModelAccessControlList 
  # @return [OrgSagebionetworksRepoModelAccessControlList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1EntityIdAnnotations2", {
  # tests for putRepoV1EntityIdAnnotations2
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character - The id of the entity to update.
  # @param org_sagebionetworks_repo_model_annotation_v2_annotations OrgSagebionetworksRepoModelAnnotationV2Annotations 
  # @return [OrgSagebionetworksRepoModelAnnotationV2Annotations]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1EntityIdDatatype", {
  # tests for putRepoV1EntityIdDatatype
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @param type OrgSagebionetworksRepoModelDataType 
  # @return [OrgSagebionetworksRepoModelDataTypeResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1EntityIdGeneratedBy", {
  # tests for putRepoV1EntityIdGeneratedBy
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the entity to update.
  # @param generated_by character The id of the activity to connect to the entity. You must                     be the creator of the ,<a href=\"${org.sagebionetworks.repo.model.provenance.Activity}\">,Activity,</a>, used here.
  # @return [OrgSagebionetworksRepoModelProvenanceActivity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1EntityIdJson", {
  # tests for putRepoV1EntityIdJson
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @param body object 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1EntityIdSchemaBinding", {
  # tests for putRepoV1EntityIdSchemaBinding
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The syn ID of the entity to bind.
  # @param org_sagebionetworks_repo_model_entity_bind_schema_to_entity_request OrgSagebionetworksRepoModelEntityBindSchemaToEntityRequest 
  # @return [OrgSagebionetworksRepoModelSchemaJsonSchemaObjectBinding]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1EntityIdVersionVersionNumberFilehandle", {
  # tests for putRepoV1EntityIdVersionVersionNumberFilehandle
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The id of the file entity
  # @param version_number numeric The entity version
  # @param org_sagebionetworks_repo_model_entity_file_handle_update_request OrgSagebionetworksRepoModelEntityFileHandleUpdateRequest 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
