# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelAuthHasTwoFactorAuthToken")

model_instance <- OrgSagebionetworksRepoModelAuthHasTwoFactorAuthToken$new()

test_that("userId", {
  # tests for the property `userId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`userId`, "EXPECTED_RESULT")
})

test_that("twoFaToken", {
  # tests for the property `twoFaToken` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`twoFaToken`, "EXPECTED_RESULT")
})

test_that("otpCode", {
  # tests for the property `otpCode` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`otpCode`, "EXPECTED_RESULT")
})

test_that("otpType", {
  # tests for the property `otpType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`otpType`, "EXPECTED_RESULT")
})

test_that("newPassword", {
  # tests for the property `newPassword` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`newPassword`, "EXPECTED_RESULT")
})

test_that("concreteType", {
  # tests for the property `concreteType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})
