# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VerificationServicesApi")

api_instance <- VerificationServicesApi$new()

test_that("deleteRepoV1VerificationSubmissionId", {
  # tests for deleteRepoV1VerificationSubmissionId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id numeric 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1VerificationSubmission", {
  # tests for getRepoV1VerificationSubmission
  # base path: https://repo-prod.prod.sagebase.org
  # @param verified_user_id numeric filter on the user requesting verification (optional) (optional)
  # @param current_verification_state OrgSagebionetworksRepoModelVerificationVerificationStateEnum filter on the state of the verification submission (optional) (optional)
  # @param limit numeric page size pagination parameter (optional) (optional)
  # @param offset numeric page start pagination parameter (zero offset, optional) (optional)
  # @return [OrgSagebionetworksRepoModelVerificationVerificationPagedResults]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1VerificationSubmission", {
  # tests for postRepoV1VerificationSubmission
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_verification_verification_submission OrgSagebionetworksRepoModelVerificationVerificationSubmission 
  # @param notification_unsubscribe_endpoint character  (optional)
  # @return [OrgSagebionetworksRepoModelVerificationVerificationSubmission]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1VerificationSubmissionIdState", {
  # tests for postRepoV1VerificationSubmissionIdState
  # base path: https://repo-prod.prod.sagebase.org
  # @param id numeric the ID of the verification submission
  # @param org_sagebionetworks_repo_model_verification_verification_state OrgSagebionetworksRepoModelVerificationVerificationState 
  # @param notification_unsubscribe_endpoint character the portal prefix for one-click email unsubscription (optional)
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
