# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ActivityServicesApi")

api_instance <- ActivityServicesApi$new()

test_that("deleteRepoV1ActivityId", {
  # tests for deleteRepoV1ActivityId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The id of activity to delete.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ActivityId", {
  # tests for getRepoV1ActivityId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the activity to fetch.
  # @return [OrgSagebionetworksRepoModelProvenanceActivity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ActivityIdGenerated", {
  # tests for getRepoV1ActivityIdGenerated
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @return [PaginatedResultsOfReference]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1Activity", {
  # tests for postRepoV1Activity
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_provenance_activity OrgSagebionetworksRepoModelProvenanceActivity 
  # @return [OrgSagebionetworksRepoModelProvenanceActivity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1ActivityId", {
  # tests for putRepoV1ActivityId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The id of the activity to update.
  # @param org_sagebionetworks_repo_model_provenance_activity OrgSagebionetworksRepoModelProvenanceActivity 
  # @return [OrgSagebionetworksRepoModelProvenanceActivity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
