# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DOIServicesApi")

api_instance <- DOIServicesApi$new()

test_that("getRepoV1Doi", {
  # tests for getRepoV1Doi
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @param type OrgSagebionetworksRepoModelObjectType 
  # @param version numeric  (optional)
  # @return [OrgSagebionetworksRepoModelDoiV2Doi]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1DoiAssociation", {
  # tests for getRepoV1DoiAssociation
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @param type OrgSagebionetworksRepoModelObjectType 
  # @param version numeric  (optional)
  # @return [OrgSagebionetworksRepoModelDoiV2DoiAssociation]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1DoiAsyncGetAsyncToken", {
  # tests for getRepoV1DoiAsyncGetAsyncToken
  # base path: https://repo-prod.prod.sagebase.org
  # @param async_token character The async job token from the create/update call
  # @return [OrgSagebionetworksRepoModelDoiV2DoiResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1DoiLocate", {
  # tests for getRepoV1DoiLocate
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @param type OrgSagebionetworksRepoModelObjectType 
  # @param version numeric  (optional)
  # @param redirect character Whether to return the URL or redirect to the URL (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1DoiAsyncStart", {
  # tests for postRepoV1DoiAsyncStart
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_doi_v2_doi_request OrgSagebionetworksRepoModelDoiV2DoiRequest 
  # @return [OrgSagebionetworksRepoModelAsynchAsyncJobId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
