# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DataAccessServicesApi")

api_instance <- DataAccessServicesApi$new()

test_that("deleteRepoV1DataAccessSubmissionSubmissionId", {
  # tests for deleteRepoV1DataAccessSubmissionSubmissionId
  # base path: https://repo-prod.prod.sagebase.org
  # @param submission_id character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1AccessRequirementRequirementIdDataAccessRequestForUpdate", {
  # tests for getRepoV1AccessRequirementRequirementIdDataAccessRequestForUpdate
  # base path: https://repo-prod.prod.sagebase.org
  # @param requirement_id character 
  # @return [OrgSagebionetworksRepoModelDataaccessRequestInterface]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1AccessRequirementRequirementIdResearchProjectForUpdate", {
  # tests for getRepoV1AccessRequirementRequirementIdResearchProjectForUpdate
  # base path: https://repo-prod.prod.sagebase.org
  # @param requirement_id character 
  # @return [OrgSagebionetworksRepoModelDataaccessResearchProject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1AccessRequirementRequirementIdStatus", {
  # tests for getRepoV1AccessRequirementRequirementIdStatus
  # base path: https://repo-prod.prod.sagebase.org
  # @param requirement_id character 
  # @return [OrgSagebionetworksRepoModelDataaccessAccessRequirementStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1DataAccessSubmissionOpenSubmissions", {
  # tests for getRepoV1DataAccessSubmissionOpenSubmissions
  # base path: https://repo-prod.prod.sagebase.org
  # @param next_page_token character  (optional)
  # @return [OrgSagebionetworksRepoModelDataaccessOpenSubmissionPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1DataAccessSubmissionSubmissionId", {
  # tests for getRepoV1DataAccessSubmissionSubmissionId
  # base path: https://repo-prod.prod.sagebase.org
  # @param submission_id character 
  # @return [OrgSagebionetworksRepoModelDataaccessSubmission]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1AccessRequirementRequirementIdApprovedSubmissionInfo", {
  # tests for postRepoV1AccessRequirementRequirementIdApprovedSubmissionInfo
  # base path: https://repo-prod.prod.sagebase.org
  # @param requirement_id character 
  # @param org_sagebionetworks_repo_model_dataaccess_submission_info_page_request OrgSagebionetworksRepoModelDataaccessSubmissionInfoPageRequest 
  # @return [OrgSagebionetworksRepoModelDataaccessSubmissionInfoPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1AccessRequirementRequirementIdSubmissions", {
  # tests for postRepoV1AccessRequirementRequirementIdSubmissions
  # base path: https://repo-prod.prod.sagebase.org
  # @param requirement_id character 
  # @param org_sagebionetworks_repo_model_dataaccess_submission_page_request OrgSagebionetworksRepoModelDataaccessSubmissionPageRequest 
  # @return [OrgSagebionetworksRepoModelDataaccessSubmissionPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1DataAccessRequest", {
  # tests for postRepoV1DataAccessRequest
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_dataaccess_request_interface OrgSagebionetworksRepoModelDataaccessRequestInterface 
  # @return [OrgSagebionetworksRepoModelDataaccessRequestInterface]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1DataAccessRequestRequestIdSubmission", {
  # tests for postRepoV1DataAccessRequestRequestIdSubmission
  # base path: https://repo-prod.prod.sagebase.org
  # @param request_id character - The ID of the request object.
  # @param org_sagebionetworks_repo_model_dataaccess_create_submission_request OrgSagebionetworksRepoModelDataaccessCreateSubmissionRequest 
  # @return [OrgSagebionetworksRepoModelDataaccessSubmissionStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1DataAccessSubmissionSearch", {
  # tests for postRepoV1DataAccessSubmissionSearch
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_dataaccess_submission_search_request OrgSagebionetworksRepoModelDataaccessSubmissionSearchRequest 
  # @return [OrgSagebionetworksRepoModelDataaccessSubmissionSearchResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1ResearchProject", {
  # tests for postRepoV1ResearchProject
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_dataaccess_research_project OrgSagebionetworksRepoModelDataaccessResearchProject 
  # @return [OrgSagebionetworksRepoModelDataaccessResearchProject]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1RestrictionInformation", {
  # tests for postRepoV1RestrictionInformation
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_restriction_information_request OrgSagebionetworksRepoModelRestrictionInformationRequest 
  # @return [OrgSagebionetworksRepoModelRestrictionInformationResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1DataAccessSubmissionSubmissionId", {
  # tests for putRepoV1DataAccessSubmissionSubmissionId
  # base path: https://repo-prod.prod.sagebase.org
  # @param submission_id character 
  # @param org_sagebionetworks_repo_model_dataaccess_submission_state_change_request OrgSagebionetworksRepoModelDataaccessSubmissionStateChangeRequest 
  # @return [OrgSagebionetworksRepoModelDataaccessSubmission]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1DataAccessSubmissionSubmissionIdCancellation", {
  # tests for putRepoV1DataAccessSubmissionSubmissionIdCancellation
  # base path: https://repo-prod.prod.sagebase.org
  # @param submission_id character - The ID of the submission to cancel.
  # @return [OrgSagebionetworksRepoModelDataaccessSubmissionStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
