# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FormServicesApi")

api_instance <- FormServicesApi$new()

test_that("deleteRepoV1FormDataId", {
  # tests for deleteRepoV1FormDataId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character Id of the FormData object to delete
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1FormGroupId", {
  # tests for getRepoV1FormGroupId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @return [OrgSagebionetworksRepoModelFormFormGroup]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1FormGroupIdAcl", {
  # tests for getRepoV1FormGroupIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The identifier of the FormGroup.
  # @return [OrgSagebionetworksRepoModelAccessControlList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1FormData", {
  # tests for postRepoV1FormData
  # base path: https://repo-prod.prod.sagebase.org
  # @param group_id character The identifier of the group that manages this data.                          Required.
  # @param org_sagebionetworks_repo_model_form_form_change_request OrgSagebionetworksRepoModelFormFormChangeRequest 
  # @return [OrgSagebionetworksRepoModelFormFormData]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1FormDataIdSubmit", {
  # tests for postRepoV1FormDataIdSubmit
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @return [OrgSagebionetworksRepoModelFormFormData]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1FormDataList", {
  # tests for postRepoV1FormDataList
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_form_list_request OrgSagebionetworksRepoModelFormListRequest 
  # @return [OrgSagebionetworksRepoModelFormListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1FormDataListReviewer", {
  # tests for postRepoV1FormDataListReviewer
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_form_list_request OrgSagebionetworksRepoModelFormListRequest 
  # @return [OrgSagebionetworksRepoModelFormListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1FormGroup", {
  # tests for postRepoV1FormGroup
  # base path: https://repo-prod.prod.sagebase.org
  # @param name character A globally unique name for the group. Required. Between 3 and                256 characters.
  # @return [OrgSagebionetworksRepoModelFormFormGroup]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1FormDataId", {
  # tests for putRepoV1FormDataId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The identifier of the FormData to update.
  # @param org_sagebionetworks_repo_model_form_form_change_request OrgSagebionetworksRepoModelFormFormChangeRequest 
  # @return [OrgSagebionetworksRepoModelFormFormData]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1FormDataIdAccept", {
  # tests for putRepoV1FormDataIdAccept
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character Identifier of the FormData to accept.
  # @return [OrgSagebionetworksRepoModelFormFormData]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1FormDataIdReject", {
  # tests for putRepoV1FormDataIdReject
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character Identifier of the FormData to accept.
  # @param org_sagebionetworks_repo_model_form_form_rejection OrgSagebionetworksRepoModelFormFormRejection 
  # @return [OrgSagebionetworksRepoModelFormFormData]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1FormGroupIdAcl", {
  # tests for putRepoV1FormGroupIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The identifier of the FormGroup.
  # @param org_sagebionetworks_repo_model_access_control_list OrgSagebionetworksRepoModelAccessControlList 
  # @return [OrgSagebionetworksRepoModelAccessControlList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
