# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WikiPageServicesApi")

api_instance <- WikiPageServicesApi$new()

test_that("deleteRepoV1EntityOwnerIdWikiWikiId", {
  # tests for deleteRepoV1EntityOwnerIdWikiWikiId
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Entity.
  # @param wiki_id character The ID of the WikiPage to delete.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("deleteRepoV1EvaluationOwnerIdWikiWikiId", {
  # tests for deleteRepoV1EvaluationOwnerIdWikiWikiId
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Evaluations.
  # @param wiki_id character The ID of the WikiPage to delete.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1AccessRequirementOwnerIdWikiWikiId", {
  # tests for getRepoV1AccessRequirementOwnerIdWikiWikiId
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Entity.
  # @param wiki_id character The ID of the WikiPage to get.
  # @param wiki_version numeric When included returns a specific version of a wiki. (optional)
  # @return [OrgSagebionetworksRepoModelWikiWikiPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1AccessRequirementOwnerIdWikikey", {
  # tests for getRepoV1AccessRequirementOwnerIdWikikey
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Access Requirement.
  # @return [OrgSagebionetworksRepoModelDaoWikiPageKey]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityOwnerIdWiki", {
  # tests for getRepoV1EntityOwnerIdWiki
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Entity.
  # @return [OrgSagebionetworksRepoModelWikiWikiPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityOwnerIdWikiWikiId", {
  # tests for getRepoV1EntityOwnerIdWikiWikiId
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Entity.
  # @param wiki_id character The ID of the WikiPage to get.
  # @param wiki_version numeric When included returns a specific version of a wiki. (optional)
  # @return [OrgSagebionetworksRepoModelWikiWikiPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityOwnerIdWikiWikiIdAttachment", {
  # tests for getRepoV1EntityOwnerIdWikiWikiIdAttachment
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Entity
  # @param wiki_id character The ID of the WikiPage
  # @param file_name character The name of the file to get. The file names can be found in             the FileHandles from the ,<a href=\"${GET.entity.ownerId.wiki.wikiId.attachmenthandles}\">,GET             /entity/{ownerId}/wiki/{wikiId}/attachmenthandles,</a>, method.
  # @param redirect character When set to false, the URL will be returned as text/plain             instead of redirecting. (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityOwnerIdWikiWikiIdAttachmenthandles", {
  # tests for getRepoV1EntityOwnerIdWikiWikiIdAttachmenthandles
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Entity.
  # @param wiki_id character The ID of the WikiPage.
  # @return [OrgSagebionetworksRepoModelFileFileHandleResults]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityOwnerIdWikiWikiIdAttachmentpreview", {
  # tests for getRepoV1EntityOwnerIdWikiWikiIdAttachmentpreview
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Entity
  # @param wiki_id character The ID of the WikiPage
  # @param file_name character The name of the file to get. The file names can be found in             the FileHandles from the ,<a href=\"${GET.entity.ownerId.wiki.wikiId.attachmenthandles}\">,GET             /entity/{ownerId}/wiki/{wikiId}/attachmenthandles,</a>, method.
  # @param redirect character When set to false, the URL will be returned as text/plain             instead of redirecting. (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityOwnerIdWikiheadertree", {
  # tests for getRepoV1EntityOwnerIdWikiheadertree
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Entity.
  # @param offset numeric The index of the pagination offset. For a page size of 10, the             first page would be at offset = 0, and the second page would             be at offset = 10. (optional)
  # @param limit numeric Limits the size of the page returned. For example, a page size             of 10 require limit = 10. (optional)
  # @return [PaginatedResultsOfWikiHeader]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityOwnerIdWikikey", {
  # tests for getRepoV1EntityOwnerIdWikikey
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Entity.
  # @return [OrgSagebionetworksRepoModelDaoWikiPageKey]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EvaluationOwnerIdWiki", {
  # tests for getRepoV1EvaluationOwnerIdWiki
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Evaluation.
  # @return [OrgSagebionetworksRepoModelWikiWikiPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EvaluationOwnerIdWikiWikiId", {
  # tests for getRepoV1EvaluationOwnerIdWikiWikiId
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Evaluation.
  # @param wiki_id character The ID of the WikiPage to get.
  # @param wiki_version numeric  (optional)
  # @return [OrgSagebionetworksRepoModelWikiWikiPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EvaluationOwnerIdWikiWikiIdAttachment", {
  # tests for getRepoV1EvaluationOwnerIdWikiWikiIdAttachment
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Evaluation
  # @param wiki_id character The ID of the WikiPage
  # @param file_name character The name of the file to get. The file names can be found in             the FileHandles from the ,<a href=\"${GET.evaluation.ownerId.wiki.wikiId.attachmenthandles}\">,GET /evaluation/{ownerId}/wiki/{wikiId}/attachmenthandles,</a>,             method.
  # @param redirect character When set to false, the URL will be returned as text/plain             instead of redirecting. (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EvaluationOwnerIdWikiWikiIdAttachmenthandles", {
  # tests for getRepoV1EvaluationOwnerIdWikiWikiIdAttachmenthandles
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Evaluation.
  # @param wiki_id character The ID of the WikiPage.
  # @return [OrgSagebionetworksRepoModelFileFileHandleResults]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EvaluationOwnerIdWikiWikiIdAttachmentpreview", {
  # tests for getRepoV1EvaluationOwnerIdWikiWikiIdAttachmentpreview
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Evaluation
  # @param wiki_id character The ID of the WikiPage
  # @param file_name character The name of the file to get. The file names can be found in             the FileHandles from the ,<a href=\"${GET.evaluation.ownerId.wiki.wikiId.attachmenthandles}\">,GET /evaluation/{ownerId}/wiki/{wikiId}/attachmenthandles,</a>,             method.
  # @param redirect character When set to false, the URL will be returned as text/plain             instead of redirecting. (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EvaluationOwnerIdWikiheadertree", {
  # tests for getRepoV1EvaluationOwnerIdWikiheadertree
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Evaluation.
  # @param offset numeric The index of the pagination offset. For a page size of 10, the             first page would be at offset = 0, and the second page would             be at offset = 10. (optional)
  # @param limit numeric Limits the size of the page returned. For example, a page size             of 10 require limit = 10. (optional)
  # @return [PaginatedResultsOfWikiHeader]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EvaluationOwnerIdWikikey", {
  # tests for getRepoV1EvaluationOwnerIdWikikey
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Evaluation.
  # @return [OrgSagebionetworksRepoModelDaoWikiPageKey]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1AccessRequirementOwnerIdWiki", {
  # tests for postRepoV1AccessRequirementOwnerIdWiki
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owner Entity.
  # @param org_sagebionetworks_repo_model_wiki_wiki_page OrgSagebionetworksRepoModelWikiWikiPage 
  # @return [OrgSagebionetworksRepoModelWikiWikiPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1EntityOwnerIdWiki", {
  # tests for postRepoV1EntityOwnerIdWiki
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owner Entity.
  # @param org_sagebionetworks_repo_model_wiki_wiki_page OrgSagebionetworksRepoModelWikiWikiPage 
  # @return [OrgSagebionetworksRepoModelWikiWikiPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1EvaluationOwnerIdWiki", {
  # tests for postRepoV1EvaluationOwnerIdWiki
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owner Evaluation.
  # @param org_sagebionetworks_repo_model_wiki_wiki_page OrgSagebionetworksRepoModelWikiWikiPage 
  # @return [OrgSagebionetworksRepoModelWikiWikiPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1AccessRequirementOwnerIdWikiWikiId", {
  # tests for putRepoV1AccessRequirementOwnerIdWikiWikiId
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Entity.
  # @param wiki_id character The ID of the WikiPage to update.
  # @param org_sagebionetworks_repo_model_wiki_wiki_page OrgSagebionetworksRepoModelWikiWikiPage 
  # @return [OrgSagebionetworksRepoModelWikiWikiPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1EntityOwnerIdWikiWikiId", {
  # tests for putRepoV1EntityOwnerIdWikiWikiId
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Entity.
  # @param wiki_id character The ID of the WikiPage to update.
  # @param org_sagebionetworks_repo_model_wiki_wiki_page OrgSagebionetworksRepoModelWikiWikiPage 
  # @return [OrgSagebionetworksRepoModelWikiWikiPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1EvaluationOwnerIdWikiWikiId", {
  # tests for putRepoV1EvaluationOwnerIdWikiWikiId
  # base path: https://repo-prod.prod.sagebase.org
  # @param owner_id character The ID of the owning Evaluation.
  # @param wiki_id character The ID of the WikiPage to update.
  # @param org_sagebionetworks_repo_model_wiki_wiki_page OrgSagebionetworksRepoModelWikiWikiPage 
  # @return [OrgSagebionetworksRepoModelWikiWikiPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
