# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DiscussionServicesApi")

api_instance <- DiscussionServicesApi$new()

test_that("deleteRepoV1ReplyReplyId", {
  # tests for deleteRepoV1ReplyReplyId
  # base path: https://repo-prod.prod.sagebase.org
  # @param reply_id character - the ID of the reply being marked as deleted
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("deleteRepoV1ThreadThreadId", {
  # tests for deleteRepoV1ThreadThreadId
  # base path: https://repo-prod.prod.sagebase.org
  # @param thread_id character - the ID of the thread being marked as deleted
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdThreads", {
  # tests for getRepoV1EntityIdThreads
  # base path: https://repo-prod.prod.sagebase.org
  # @param limit numeric - Limits the size of the page returned. For example, a page size of 10 require limit = 10. The maximum Limit for this call is 20.
  # @param offset numeric - The index of the pagination offset. For a page size of 10, the first page would be at offset = 0, and the second page would be at offset = 10.
  # @param id character - The request entityId
  # @param sort OrgSagebionetworksRepoModelDiscussionDiscussionThreadOrder - The field to sort the resulting threads on. Available options: ,<a href=\"${org.sagebionetworks.repo.model.discussion.DiscussionThreadOrder}\">,DiscussionThreadOrder,</a>,. (optional)
  # @param ascending character - The direction of sort: true for ascending, and false for descending (optional)
  # @return [PaginatedResultsOfDiscussionThreadBundle]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ForumForumId", {
  # tests for getRepoV1ForumForumId
  # base path: https://repo-prod.prod.sagebase.org
  # @param forum_id character - The ID of the forum.
  # @return [OrgSagebionetworksRepoModelDiscussionForum]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ForumForumIdModerators", {
  # tests for getRepoV1ForumForumIdModerators
  # base path: https://repo-prod.prod.sagebase.org
  # @param limit numeric - Limits the size of the page returned. For example, a page size of 10 require limit = 10. The maximum Limit for this call is 100.
  # @param offset numeric - The index of the pagination offset. For a page size of 10, the first page would be at offset = 0, and the second page would be at offset = 10.
  # @param forum_id character - The forum ID to which the returning mederators belong
  # @return [OrgSagebionetworksRepoModelPaginatedIds]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ForumForumIdThreadcount", {
  # tests for getRepoV1ForumForumIdThreadcount
  # base path: https://repo-prod.prod.sagebase.org
  # @param filter OrgSagebionetworksRepoModelDiscussionDiscussionFilter - Filter deleted/ not deleted threads. Available options: ,<a href=\"${org.sagebionetworks.repo.model.discussion.DiscussionFilter}\">,DiscussionFilter,</a>,.
  # @param forum_id character - The forum ID to which the returning threads belong
  # @return [OrgSagebionetworksRepoModelDiscussionThreadCount]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ForumForumIdThreads", {
  # tests for getRepoV1ForumForumIdThreads
  # base path: https://repo-prod.prod.sagebase.org
  # @param limit numeric - Limits the size of the page returned. For example, a page size of 10 require limit = 10. The maximum Limit for this call is 20.
  # @param offset numeric - The index of the pagination offset. For a page size of 10, the first page would be at offset = 0, and the second page would be at offset = 10.
  # @param filter OrgSagebionetworksRepoModelDiscussionDiscussionFilter - Filter deleted/ not deleted threads. Available options: ,<a href=\"${org.sagebionetworks.repo.model.discussion.DiscussionFilter}\">,DiscussionFilter,</a>,.
  # @param forum_id character - The forum ID to which the returning threads belong
  # @param sort OrgSagebionetworksRepoModelDiscussionDiscussionThreadOrder - The field to sort the resulting threads on. Available options: ,<a href=\"${org.sagebionetworks.repo.model.discussion.DiscussionThreadOrder}\">,DiscussionThreadOrder,</a>,. (optional)
  # @param ascending character - The direction of sort: true for ascending, and false for descending (optional)
  # @return [PaginatedResultsOfDiscussionThreadBundle]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ProjectProjectIdForum", {
  # tests for getRepoV1ProjectProjectIdForum
  # base path: https://repo-prod.prod.sagebase.org
  # @param project_id character - The ID of the project to which the forum belongs.
  # @return [OrgSagebionetworksRepoModelDiscussionForum]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ReplyMessageUrl", {
  # tests for getRepoV1ReplyMessageUrl
  # base path: https://repo-prod.prod.sagebase.org
  # @param message_key character - DiscussionReplyBundle.messageKey
  # @return [OrgSagebionetworksRepoModelDiscussionMessageURL]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ReplyReplyId", {
  # tests for getRepoV1ReplyReplyId
  # base path: https://repo-prod.prod.sagebase.org
  # @param reply_id character - The ID of the reply being requested
  # @return [OrgSagebionetworksRepoModelDiscussionDiscussionReplyBundle]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ThreadMessageUrl", {
  # tests for getRepoV1ThreadMessageUrl
  # base path: https://repo-prod.prod.sagebase.org
  # @param message_key character 
  # @return [OrgSagebionetworksRepoModelDiscussionMessageURL]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ThreadThreadId", {
  # tests for getRepoV1ThreadThreadId
  # base path: https://repo-prod.prod.sagebase.org
  # @param thread_id character - The ID of the thread being requested
  # @return [OrgSagebionetworksRepoModelDiscussionDiscussionThreadBundle]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ThreadThreadIdReplies", {
  # tests for getRepoV1ThreadThreadIdReplies
  # base path: https://repo-prod.prod.sagebase.org
  # @param limit numeric - Limits the size of the page returned. For example, a page size of 10 require limit = 10. The maximum Limit for this call is 100.
  # @param offset numeric - The index of the pagination offset. For a page size of 10, the first page would be at offset = 0, and the second page would be at offset = 10.
  # @param filter OrgSagebionetworksRepoModelDiscussionDiscussionFilter - Filter deleted/ not deleted replies. Available options: ,<a href=\"${org.sagebionetworks.repo.model.discussion.DiscussionFilter}\">,DiscussionFilter,</a>,.
  # @param thread_id character - The thread ID to which the returning replies belong
  # @param sort OrgSagebionetworksRepoModelDiscussionDiscussionReplyOrder - The field to sort the resulting replies on. Available options: ,<a href=\"${org.sagebionetworks.repo.model.discussion.DiscussionReplyOrder}\">,DiscussionReplyOrder,</a>,. (optional)
  # @param ascending character - The direction of sort: true for ascending, and false for descending (optional)
  # @return [PaginatedResultsOfDiscussionReplyBundle]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ThreadThreadIdReplycount", {
  # tests for getRepoV1ThreadThreadIdReplycount
  # base path: https://repo-prod.prod.sagebase.org
  # @param filter OrgSagebionetworksRepoModelDiscussionDiscussionFilter - Filter deleted/ not deleted replies. Available options: ,<a href=\"${org.sagebionetworks.repo.model.discussion.DiscussionFilter}\">,DiscussionFilter,</a>,.
  # @param thread_id character - The thread ID to which the returning replies belong
  # @return [OrgSagebionetworksRepoModelDiscussionReplyCount]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1EntityThreadcounts", {
  # tests for postRepoV1EntityThreadcounts
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_entity_id_list OrgSagebionetworksRepoModelEntityIdList 
  # @return [OrgSagebionetworksRepoModelDiscussionEntityThreadCounts]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1ForumForumIdSearch", {
  # tests for postRepoV1ForumForumIdSearch
  # base path: https://repo-prod.prod.sagebase.org
  # @param forum_id character The ID of the forum where the search is performed
  # @param org_sagebionetworks_repo_model_discussion_discussion_search_request OrgSagebionetworksRepoModelDiscussionDiscussionSearchRequest 
  # @return [OrgSagebionetworksRepoModelDiscussionDiscussionSearchResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1Reply", {
  # tests for postRepoV1Reply
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_discussion_create_discussion_reply OrgSagebionetworksRepoModelDiscussionCreateDiscussionReply 
  # @return [OrgSagebionetworksRepoModelDiscussionDiscussionReplyBundle]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1Thread", {
  # tests for postRepoV1Thread
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_discussion_create_discussion_thread OrgSagebionetworksRepoModelDiscussionCreateDiscussionThread 
  # @return [OrgSagebionetworksRepoModelDiscussionDiscussionThreadBundle]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1ReplyReplyIdMessage", {
  # tests for putRepoV1ReplyReplyIdMessage
  # base path: https://repo-prod.prod.sagebase.org
  # @param reply_id character - The ID of the reply being updated
  # @param org_sagebionetworks_repo_model_discussion_update_reply_message OrgSagebionetworksRepoModelDiscussionUpdateReplyMessage 
  # @return [OrgSagebionetworksRepoModelDiscussionDiscussionReplyBundle]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1ThreadThreadIdMessage", {
  # tests for putRepoV1ThreadThreadIdMessage
  # base path: https://repo-prod.prod.sagebase.org
  # @param thread_id character - The ID of the thread being updated
  # @param org_sagebionetworks_repo_model_discussion_update_thread_message OrgSagebionetworksRepoModelDiscussionUpdateThreadMessage 
  # @return [OrgSagebionetworksRepoModelDiscussionDiscussionThreadBundle]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1ThreadThreadIdPin", {
  # tests for putRepoV1ThreadThreadIdPin
  # base path: https://repo-prod.prod.sagebase.org
  # @param thread_id character - the ID of the thread being marked as pinned
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1ThreadThreadIdRestore", {
  # tests for putRepoV1ThreadThreadIdRestore
  # base path: https://repo-prod.prod.sagebase.org
  # @param thread_id character - the ID of the thread that was marked as deleted
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1ThreadThreadIdTitle", {
  # tests for putRepoV1ThreadThreadIdTitle
  # base path: https://repo-prod.prod.sagebase.org
  # @param thread_id character - The ID of the thread being updated
  # @param org_sagebionetworks_repo_model_discussion_update_thread_title OrgSagebionetworksRepoModelDiscussionUpdateThreadTitle 
  # @return [OrgSagebionetworksRepoModelDiscussionDiscussionThreadBundle]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1ThreadThreadIdUnpin", {
  # tests for putRepoV1ThreadThreadIdUnpin
  # base path: https://repo-prod.prod.sagebase.org
  # @param thread_id character - the ID of the thread being unpinned
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
