# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ProjectSettingsServicesApi")

api_instance <- ProjectSettingsServicesApi$new()

test_that("deleteRepoV1ProjectSettingsId", {
  # tests for deleteRepoV1ProjectSettingsId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the ,<a href=\"${org.sagebionetworks.repo.model.project.ProjectSetting}\">,ProjectSetting,</a>,. This is not the ID of the project.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ProjectSettingsId", {
  # tests for getRepoV1ProjectSettingsId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character the ID of the ,<a href=\"${org.sagebionetworks.repo.model.project.ProjectSetting}\">,ProjectSetting,</a>
  # @return [OrgSagebionetworksRepoModelProjectProjectSetting]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1ProjectSettingsProjectIdTypeType", {
  # tests for getRepoV1ProjectSettingsProjectIdTypeType
  # base path: https://repo-prod.prod.sagebase.org
  # @param project_id character the ID of the project
  # @param type OrgSagebionetworksRepoModelProjectProjectSettingsType The ,<a href=\"${org.sagebionetworks.repo.model.project.ProjectSettingsType}\">,ProjectSettingsType,</a>, to get.
  # @return [OrgSagebionetworksRepoModelProjectProjectSetting]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1StorageLocationId", {
  # tests for getRepoV1StorageLocationId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id numeric the ID of the storage location setting.
  # @return [OrgSagebionetworksRepoModelProjectStorageLocationSetting]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1ProjectSettings", {
  # tests for postRepoV1ProjectSettings
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_project_project_setting OrgSagebionetworksRepoModelProjectProjectSetting 
  # @return [OrgSagebionetworksRepoModelProjectProjectSetting]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1StorageLocation", {
  # tests for postRepoV1StorageLocation
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_project_storage_location_setting OrgSagebionetworksRepoModelProjectStorageLocationSetting 
  # @return [OrgSagebionetworksRepoModelProjectStorageLocationSetting]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1ProjectSettings", {
  # tests for putRepoV1ProjectSettings
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_project_project_setting OrgSagebionetworksRepoModelProjectProjectSetting 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
