# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AccessRequirementServicesApi")

api_instance <- AccessRequirementServicesApi$new()

test_that("deleteRepoV1AccessRequirementRequirementId", {
  # tests for deleteRepoV1AccessRequirementRequirementId
  # base path: https://repo-prod.prod.sagebase.org
  # @param requirement_id character the ID of the requirement to delete
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("deleteRepoV1AccessRequirementRequirementIdAcl", {
  # tests for deleteRepoV1AccessRequirementRequirementIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param requirement_id character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1AccessRequirementRequirementId", {
  # tests for getRepoV1AccessRequirementRequirementId
  # base path: https://repo-prod.prod.sagebase.org
  # @param requirement_id character 
  # @return [OrgSagebionetworksRepoModelAccessRequirement]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1AccessRequirementRequirementIdAcl", {
  # tests for getRepoV1AccessRequirementRequirementIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param requirement_id character 
  # @return [OrgSagebionetworksRepoModelAccessControlList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1AccessRequirementRequirementIdSubjects", {
  # tests for getRepoV1AccessRequirementRequirementIdSubjects
  # base path: https://repo-prod.prod.sagebase.org
  # @param requirement_id character 
  # @param next_page_token character  (optional)
  # @return [OrgSagebionetworksRepoModelRestrictableObjectDescriptorResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1EntityIdAccessRequirement", {
  # tests for getRepoV1EntityIdAccessRequirement
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @param limit numeric - Limits the size of the page returned. For example, a page size of 10 require limit = 10. The maximum limit for this call is 50. (optional)
  # @param offset numeric - The index of the pagination offset. For a page size of 10, the first page would be at offset = 0, and the second page would be at offset = 10. (optional)
  # @return [PaginatedResultsOfAccessRequirement]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1TeamIdAccessRequirement", {
  # tests for getRepoV1TeamIdAccessRequirement
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character the ID of the Team whose Access Requirements are retrieved.
  # @param limit numeric - Limits the size of the page returned. For example, a page size of 10 require limit = 10. The maximum limit for this call is 50. (optional)
  # @param offset numeric - The index of the pagination offset. For a page size of 10, the first page would be at offset = 0, and the second page would be at offset = 10. (optional)
  # @return [PaginatedResultsOfAccessRequirement]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1AccessRequirement", {
  # tests for postRepoV1AccessRequirement
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_access_requirement OrgSagebionetworksRepoModelAccessRequirement 
  # @return [OrgSagebionetworksRepoModelAccessRequirement]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1AccessRequirementRequirementIdAcl", {
  # tests for postRepoV1AccessRequirementRequirementIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param requirement_id character 
  # @param org_sagebionetworks_repo_model_access_control_list OrgSagebionetworksRepoModelAccessControlList 
  # @return [OrgSagebionetworksRepoModelAccessControlList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1AccessRequirementSearch", {
  # tests for postRepoV1AccessRequirementSearch
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_dataaccess_access_requirement_search_request OrgSagebionetworksRepoModelDataaccessAccessRequirementSearchRequest 
  # @return [OrgSagebionetworksRepoModelDataaccessAccessRequirementSearchResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1EntityIdLockAccessRequirement", {
  # tests for postRepoV1EntityIdLockAccessRequirement
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character the ID of the entity to which an Access Requirement will be applied
  # @return [OrgSagebionetworksRepoModelAccessRequirement]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1AccessRequirementConversion", {
  # tests for putRepoV1AccessRequirementConversion
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_dataaccess_access_requirement_conversion_request OrgSagebionetworksRepoModelDataaccessAccessRequirementConversionRequest 
  # @return [OrgSagebionetworksRepoModelAccessRequirement]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1AccessRequirementRequirementId", {
  # tests for putRepoV1AccessRequirementRequirementId
  # base path: https://repo-prod.prod.sagebase.org
  # @param requirement_id character the ID of the Access Requirement to be modified.
  # @param org_sagebionetworks_repo_model_access_requirement OrgSagebionetworksRepoModelAccessRequirement 
  # @return [OrgSagebionetworksRepoModelAccessRequirement]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("putRepoV1AccessRequirementRequirementIdAcl", {
  # tests for putRepoV1AccessRequirementRequirementIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param requirement_id character 
  # @param org_sagebionetworks_repo_model_access_control_list OrgSagebionetworksRepoModelAccessControlList 
  # @return [OrgSagebionetworksRepoModelAccessControlList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
