# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SubscriptionServicesApi")

api_instance <- SubscriptionServicesApi$new()

test_that("deleteRepoV1SubscriptionAll", {
  # tests for deleteRepoV1SubscriptionAll
  # base path: https://repo-prod.prod.sagebase.org
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("deleteRepoV1SubscriptionId", {
  # tests for deleteRepoV1SubscriptionId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character - the ID of the subscription that is created when the user subscribed to the topic
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1SubscriptionAll", {
  # tests for getRepoV1SubscriptionAll
  # base path: https://repo-prod.prod.sagebase.org
  # @param limit numeric - Limits the size of the page returned. For example, a page size of 10 require limit = 10. The maximum Limit for this call is 100.
  # @param offset numeric - The index of the pagination offset. For a page size of 10, the first page would be at offset = 0, and the second page would be at offset = 10.
  # @param object_type OrgSagebionetworksRepoModelSubscriptionSubscriptionObjectType - User can use this param to filter the results by the type of object they subscribed to.
  # @param sort_by OrgSagebionetworksRepoModelSubscriptionSortByType  (optional)
  # @param sort_direction OrgSagebionetworksRepoModelSubscriptionSortDirection - When provided, the results will be sorted in this direction. (optional)
  # @return [OrgSagebionetworksRepoModelSubscriptionSubscriptionPagedResults]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("getRepoV1SubscriptionId", {
  # tests for getRepoV1SubscriptionId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character - the ID of the subscription that is created when the user subscribed to the topic
  # @return [OrgSagebionetworksRepoModelSubscriptionSubscription]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1Subscription", {
  # tests for postRepoV1Subscription
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_subscription_topic OrgSagebionetworksRepoModelSubscriptionTopic 
  # @return [OrgSagebionetworksRepoModelSubscriptionSubscription]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1SubscriptionAll", {
  # tests for postRepoV1SubscriptionAll
  # base path: https://repo-prod.prod.sagebase.org
  # @param object_type OrgSagebionetworksRepoModelSubscriptionSubscriptionObjectType - SubscriptionObjectType to subscribe to
  # @return [OrgSagebionetworksRepoModelSubscriptionSubscription]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1SubscriptionList", {
  # tests for postRepoV1SubscriptionList
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_subscription_subscription_request OrgSagebionetworksRepoModelSubscriptionSubscriptionRequest 
  # @return [OrgSagebionetworksRepoModelSubscriptionSubscriptionPagedResults]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1SubscriptionSubscribers", {
  # tests for postRepoV1SubscriptionSubscribers
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_subscription_topic OrgSagebionetworksRepoModelSubscriptionTopic 
  # @param next_page_token character  (optional)
  # @return [OrgSagebionetworksRepoModelSubscriptionSubscriberPagedResults]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("postRepoV1SubscriptionSubscribersCount", {
  # tests for postRepoV1SubscriptionSubscribersCount
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_subscription_topic OrgSagebionetworksRepoModelSubscriptionTopic 
  # @return [OrgSagebionetworksRepoModelSubscriptionSubscriberCount]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
