#' Synapse REST API
#'
#' No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#'
#' The version of the OpenAPI document: v1
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title ActivityServices operations
#' @description ActivityServicesApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ deleteRepoV1ActivityId } \emph{  }
#'
#' \itemize{
#' \item \emph{ @param } id character
#'
#'
#' \item status code : 204 | Void
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ getRepoV1ActivityId } \emph{  }
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @returnType } \link{OrgSagebionetworksRepoModelProvenanceActivity} \cr
#'
#'
#' \item status code : 200 | The requested Activity if it exists.
#'
#' \item return type : OrgSagebionetworksRepoModelProvenanceActivity
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ getRepoV1ActivityIdGenerated } \emph{  }
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } offset integer
#' \item \emph{ @param } limit integer
#' \item \emph{ @returnType } \link{PaginatedResultsOfReference} \cr
#'
#'
#' \item status code : 200 | Auto-generated description
#'
#' \item return type : PaginatedResultsOfReference
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ postRepoV1Activity } \emph{  }
#'
#' \itemize{
#' \item \emph{ @param } org_sagebionetworks_repo_model_provenance_activity \link{OrgSagebionetworksRepoModelProvenanceActivity}
#' \item \emph{ @returnType } \link{OrgSagebionetworksRepoModelProvenanceActivity} \cr
#'
#'
#' \item status code : 201 | The new ,<a href=\"${org.sagebionetworks.repo.model.provenance.Activity}\">,Activity,</a>
#'
#' \item return type : OrgSagebionetworksRepoModelProvenanceActivity
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ putRepoV1ActivityId } \emph{  }
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } org_sagebionetworks_repo_model_provenance_activity \link{OrgSagebionetworksRepoModelProvenanceActivity}
#' \item \emph{ @returnType } \link{OrgSagebionetworksRepoModelProvenanceActivity} \cr
#'
#'
#' \item status code : 200 | the updated activity
#'
#' \item return type : OrgSagebionetworksRepoModelProvenanceActivity
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  deleteRepoV1ActivityId  ####################
#'
#' library(synr)
#' var_id <- "id_example" # character | The id of activity to delete.
#'
#' api_instance <- ActivityServicesApi$new()
#'
#' # Configure HTTP bearer authorization: bearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$deleteRepoV1ActivityId(var_id)
#'
#'
#' ####################  getRepoV1ActivityId  ####################
#'
#' library(synr)
#' var_id <- "id_example" # character | The ID of the activity to fetch.
#'
#' api_instance <- ActivityServicesApi$new()
#'
#' # Configure HTTP bearer authorization: bearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$getRepoV1ActivityId(var_iddata_file = "result.txt")
#' result <- api_instance$getRepoV1ActivityId(var_id)
#' dput(result)
#'
#'
#' ####################  getRepoV1ActivityIdGenerated  ####################
#'
#' library(synr)
#' var_id <- "id_example" # character | 
#' var_offset <- 56 # integer |  (Optional)
#' var_limit <- 56 # integer |  (Optional)
#'
#' api_instance <- ActivityServicesApi$new()
#'
#' # Configure HTTP bearer authorization: bearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$getRepoV1ActivityIdGenerated(var_id, offset = var_offset, limit = var_limitdata_file = "result.txt")
#' result <- api_instance$getRepoV1ActivityIdGenerated(var_id, offset = var_offset, limit = var_limit)
#' dput(result)
#'
#'
#' ####################  postRepoV1Activity  ####################
#'
#' library(synr)
#' var_org_sagebionetworks_repo_model_provenance_activity <- org.sagebionetworks.repo.model.provenance.Activity$new("id_example", "name_example", "description_example", "etag_example", "createdOn_example", "modifiedOn_example", "createdBy_example", "modifiedBy_example", c(org.sagebionetworks.repo.model.provenance.Used$new("concreteType_example", "wasExecuted_example", "name_example", "url_example", org.sagebionetworks.repo.model.Reference$new("targetId_example", 123)))) # OrgSagebionetworksRepoModelProvenanceActivity | 
#'
#' api_instance <- ActivityServicesApi$new()
#'
#' # Configure HTTP bearer authorization: bearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$postRepoV1Activity(var_org_sagebionetworks_repo_model_provenance_activitydata_file = "result.txt")
#' result <- api_instance$postRepoV1Activity(var_org_sagebionetworks_repo_model_provenance_activity)
#' dput(result)
#'
#'
#' ####################  putRepoV1ActivityId  ####################
#'
#' library(synr)
#' var_id <- "id_example" # character | The id of the activity to update.
#' var_org_sagebionetworks_repo_model_provenance_activity <- org.sagebionetworks.repo.model.provenance.Activity$new("id_example", "name_example", "description_example", "etag_example", "createdOn_example", "modifiedOn_example", "createdBy_example", "modifiedBy_example", c(org.sagebionetworks.repo.model.provenance.Used$new("concreteType_example", "wasExecuted_example", "name_example", "url_example", org.sagebionetworks.repo.model.Reference$new("targetId_example", 123)))) # OrgSagebionetworksRepoModelProvenanceActivity | 
#'
#' api_instance <- ActivityServicesApi$new()
#'
#' # Configure HTTP bearer authorization: bearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$putRepoV1ActivityId(var_id, var_org_sagebionetworks_repo_model_provenance_activitydata_file = "result.txt")
#' result <- api_instance$putRepoV1ActivityId(var_id, var_org_sagebionetworks_repo_model_provenance_activity)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
ActivityServicesApi <- R6::R6Class(
  "ActivityServicesApi",
  public = list(
    api_client = NULL,
    #' Initialize a new ActivityServicesApi.
    #'
    #' @description
    #' Initialize a new ActivityServicesApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' 
    #'
    #' @description
    #' 
    #'
    #' @param id The id of activity to delete.
    #' @param ... Other optional arguments
    #' @return void
    #' @export
    deleteRepoV1ActivityId = function(id, ...) {
      local_var_response <- self$deleteRepoV1ActivityIdWithHttpInfo(id, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' 
    #'
    #' @description
    #' 
    #'
    #' @param id The id of activity to delete.
    #' @param ... Other optional arguments
    #' @return API response (void) with additional information such as HTTP status code, headers
    #' @export
    deleteRepoV1ActivityIdWithHttpInfo = function(id, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }


      local_var_url_path <- "/repo/v1/activity/{id}"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "DELETE",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' 
    #'
    #' @description
    #' 
    #'
    #' @param id The ID of the activity to fetch.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return OrgSagebionetworksRepoModelProvenanceActivity
    #' @export
    getRepoV1ActivityId = function(id, data_file = NULL, ...) {
      local_var_response <- self$getRepoV1ActivityIdWithHttpInfo(id, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' 
    #'
    #' @description
    #' 
    #'
    #' @param id The ID of the activity to fetch.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (OrgSagebionetworksRepoModelProvenanceActivity) with additional information such as HTTP status code, headers
    #' @export
    getRepoV1ActivityIdWithHttpInfo = function(id, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }


      local_var_url_path <- "/repo/v1/activity/{id}"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response_as_text(), "OrgSagebionetworksRepoModelProvenanceActivity", loadNamespace("synr")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' 
    #'
    #' @description
    #' 
    #'
    #' @param id 
    #' @param offset (optional) No description
    #' @param limit (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return PaginatedResultsOfReference
    #' @export
    getRepoV1ActivityIdGenerated = function(id, offset = NULL, limit = NULL, data_file = NULL, ...) {
      local_var_response <- self$getRepoV1ActivityIdGeneratedWithHttpInfo(id, offset, limit, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' 
    #'
    #' @description
    #' 
    #'
    #' @param id 
    #' @param offset (optional) No description
    #' @param limit (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (PaginatedResultsOfReference) with additional information such as HTTP status code, headers
    #' @export
    getRepoV1ActivityIdGeneratedWithHttpInfo = function(id, offset = NULL, limit = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }




      query_params[["offset"]] <- `offset`

      query_params[["limit"]] <- `limit`

      local_var_url_path <- "/repo/v1/activity/{id}/generated"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response_as_text(), "PaginatedResultsOfReference", loadNamespace("synr")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' 
    #'
    #' @description
    #' 
    #'
    #' @param org_sagebionetworks_repo_model_provenance_activity 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return OrgSagebionetworksRepoModelProvenanceActivity
    #' @export
    postRepoV1Activity = function(org_sagebionetworks_repo_model_provenance_activity, data_file = NULL, ...) {
      local_var_response <- self$postRepoV1ActivityWithHttpInfo(org_sagebionetworks_repo_model_provenance_activity, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' 
    #'
    #' @description
    #' 
    #'
    #' @param org_sagebionetworks_repo_model_provenance_activity 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (OrgSagebionetworksRepoModelProvenanceActivity) with additional information such as HTTP status code, headers
    #' @export
    postRepoV1ActivityWithHttpInfo = function(org_sagebionetworks_repo_model_provenance_activity, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`org_sagebionetworks_repo_model_provenance_activity`)) {
        stop("Missing required parameter `org_sagebionetworks_repo_model_provenance_activity`.")
      }


      if (!is.null(`org_sagebionetworks_repo_model_provenance_activity`)) {
        local_var_body <- `org_sagebionetworks_repo_model_provenance_activity`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/repo/v1/activity"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response_as_text(), "OrgSagebionetworksRepoModelProvenanceActivity", loadNamespace("synr")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' 
    #'
    #' @description
    #' 
    #'
    #' @param id The id of the activity to update.
    #' @param org_sagebionetworks_repo_model_provenance_activity 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return OrgSagebionetworksRepoModelProvenanceActivity
    #' @export
    putRepoV1ActivityId = function(id, org_sagebionetworks_repo_model_provenance_activity, data_file = NULL, ...) {
      local_var_response <- self$putRepoV1ActivityIdWithHttpInfo(id, org_sagebionetworks_repo_model_provenance_activity, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' 
    #'
    #' @description
    #' 
    #'
    #' @param id The id of the activity to update.
    #' @param org_sagebionetworks_repo_model_provenance_activity 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (OrgSagebionetworksRepoModelProvenanceActivity) with additional information such as HTTP status code, headers
    #' @export
    putRepoV1ActivityIdWithHttpInfo = function(id, org_sagebionetworks_repo_model_provenance_activity, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (missing(`org_sagebionetworks_repo_model_provenance_activity`)) {
        stop("Missing required parameter `org_sagebionetworks_repo_model_provenance_activity`.")
      }



      if (!is.null(`org_sagebionetworks_repo_model_provenance_activity`)) {
        local_var_body <- `org_sagebionetworks_repo_model_provenance_activity`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/repo/v1/activity/{id}"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "PUT",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response_as_text(), "OrgSagebionetworksRepoModelProvenanceActivity", loadNamespace("synr")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
