#' Create a new OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken
#'
#' @description
#' Used to change the user password when two factor authentication is enabled. The twoFaToken is generated by the server and included in the 401 response the user tries to update the password with either the old password or a token. Only TOTP and RECOVERY_CODE otp codes can be used for this operation.
#'
#' @docType class
#' @title OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken
#' @description OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken Class
#' @format An \code{R6Class} generator object
#' @field newPassword  character [optional]
#' @field concreteType  character
#' @field userId  integer [optional]
#' @field twoFaToken  character [optional]
#' @field otpCode  character [optional]
#' @field otpType  character [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken <- R6::R6Class(
  "OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken",
  public = list(
    `newPassword` = NULL,
    `concreteType` = NULL,
    `userId` = NULL,
    `twoFaToken` = NULL,
    `otpCode` = NULL,
    `otpType` = NULL,
    #' Initialize a new OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken class.
    #'
    #' @description
    #' Initialize a new OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken class.
    #'
    #' @param concreteType concreteType
    #' @param newPassword newPassword
    #' @param userId userId
    #' @param twoFaToken twoFaToken
    #' @param otpCode otpCode
    #' @param otpType otpType
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(`concreteType`, `newPassword` = NULL, `userId` = NULL, `twoFaToken` = NULL, `otpCode` = NULL, `otpType` = NULL, ...) {
      if (!missing(`concreteType`)) {
        if (!(`concreteType` %in% c("org.sagebionetworks.repo.model.auth.ChangePasswordWithTwoFactorAuthToken"))) {
          stop(paste("Error! \"", `concreteType`, "\" cannot be assigned to `concreteType`. Must be \"org.sagebionetworks.repo.model.auth.ChangePasswordWithTwoFactorAuthToken\".", sep = ""))
        }
        if (!(is.character(`concreteType`) && length(`concreteType`) == 1)) {
          stop(paste("Error! Invalid data for `concreteType`. Must be a string:", `concreteType`))
        }
        self$`concreteType` <- `concreteType`
      }
      if (!is.null(`newPassword`)) {
        if (!(is.character(`newPassword`) && length(`newPassword`) == 1)) {
          stop(paste("Error! Invalid data for `newPassword`. Must be a string:", `newPassword`))
        }
        self$`newPassword` <- `newPassword`
      }
      if (!is.null(`userId`)) {
        if (!(is.numeric(`userId`) && length(`userId`) == 1)) {
          stop(paste("Error! Invalid data for `userId`. Must be an integer:", `userId`))
        }
        self$`userId` <- `userId`
      }
      if (!is.null(`twoFaToken`)) {
        if (!(is.character(`twoFaToken`) && length(`twoFaToken`) == 1)) {
          stop(paste("Error! Invalid data for `twoFaToken`. Must be a string:", `twoFaToken`))
        }
        self$`twoFaToken` <- `twoFaToken`
      }
      if (!is.null(`otpCode`)) {
        if (!(is.character(`otpCode`) && length(`otpCode`) == 1)) {
          stop(paste("Error! Invalid data for `otpCode`. Must be a string:", `otpCode`))
        }
        self$`otpCode` <- `otpCode`
      }
      if (!is.null(`otpType`)) {
        if (!(is.character(`otpType`) && length(`otpType`) == 1)) {
          stop(paste("Error! Invalid data for `otpType`. Must be a string:", `otpType`))
        }
        self$`otpType` <- `otpType`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken in JSON format
    #' @export
    toJSON = function() {
      OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthTokenObject <- list()
      if (!is.null(self$`newPassword`)) {
        OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthTokenObject[["newPassword"]] <-
          self$`newPassword`
      }
      if (!is.null(self$`concreteType`)) {
        OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthTokenObject[["concreteType"]] <-
          self$`concreteType`
      }
      if (!is.null(self$`userId`)) {
        OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthTokenObject[["userId"]] <-
          self$`userId`
      }
      if (!is.null(self$`twoFaToken`)) {
        OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthTokenObject[["twoFaToken"]] <-
          self$`twoFaToken`
      }
      if (!is.null(self$`otpCode`)) {
        OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthTokenObject[["otpCode"]] <-
          self$`otpCode`
      }
      if (!is.null(self$`otpType`)) {
        OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthTokenObject[["otpType"]] <-
          self$`otpType`
      }
      OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthTokenObject
    },
    #' Deserialize JSON string into an instance of OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken
    #'
    #' @description
    #' Deserialize JSON string into an instance of OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken
    #'
    #' @param input_json the JSON input
    #' @return the instance of OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`newPassword`)) {
        self$`newPassword` <- this_object$`newPassword`
      }
      if (!is.null(this_object$`concreteType`)) {
        if (!is.null(this_object$`concreteType`) && !(this_object$`concreteType` %in% c("org.sagebionetworks.repo.model.auth.ChangePasswordWithTwoFactorAuthToken"))) {
          stop(paste("Error! \"", this_object$`concreteType`, "\" cannot be assigned to `concreteType`. Must be \"org.sagebionetworks.repo.model.auth.ChangePasswordWithTwoFactorAuthToken\".", sep = ""))
        }
        self$`concreteType` <- this_object$`concreteType`
      }
      if (!is.null(this_object$`userId`)) {
        self$`userId` <- this_object$`userId`
      }
      if (!is.null(this_object$`twoFaToken`)) {
        self$`twoFaToken` <- this_object$`twoFaToken`
      }
      if (!is.null(this_object$`otpCode`)) {
        self$`otpCode` <- this_object$`otpCode`
      }
      if (!is.null(this_object$`otpType`)) {
        self$`otpType` <- this_object$`otpType`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`newPassword`)) {
          sprintf(
          '"newPassword":
            "%s"
                    ',
          self$`newPassword`
          )
        },
        if (!is.null(self$`concreteType`)) {
          sprintf(
          '"concreteType":
            "%s"
                    ',
          self$`concreteType`
          )
        },
        if (!is.null(self$`userId`)) {
          sprintf(
          '"userId":
            %d
                    ',
          self$`userId`
          )
        },
        if (!is.null(self$`twoFaToken`)) {
          sprintf(
          '"twoFaToken":
            "%s"
                    ',
          self$`twoFaToken`
          )
        },
        if (!is.null(self$`otpCode`)) {
          sprintf(
          '"otpCode":
            "%s"
                    ',
          self$`otpCode`
          )
        },
        if (!is.null(self$`otpType`)) {
          sprintf(
          '"otpType":
            "%s"
                    ',
          self$`otpType`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      json_string <- as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken
    #'
    #' @description
    #' Deserialize JSON string into an instance of OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken
    #'
    #' @param input_json the JSON input
    #' @return the instance of OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`newPassword` <- this_object$`newPassword`
      if (!is.null(this_object$`concreteType`) && !(this_object$`concreteType` %in% c("org.sagebionetworks.repo.model.auth.ChangePasswordWithTwoFactorAuthToken"))) {
        stop(paste("Error! \"", this_object$`concreteType`, "\" cannot be assigned to `concreteType`. Must be \"org.sagebionetworks.repo.model.auth.ChangePasswordWithTwoFactorAuthToken\".", sep = ""))
      }
      self$`concreteType` <- this_object$`concreteType`
      self$`userId` <- this_object$`userId`
      self$`twoFaToken` <- this_object$`twoFaToken`
      self$`otpCode` <- this_object$`otpCode`
      self$`otpType` <- this_object$`otpType`
      self
    },
    #' Validate JSON input with respect to OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken
    #'
    #' @description
    #' Validate JSON input with respect to OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `concreteType`
      if (!is.null(input_json$`concreteType`)) {
        if (!(is.character(input_json$`concreteType`) && length(input_json$`concreteType`) == 1)) {
          stop(paste("Error! Invalid data for `concreteType`. Must be a string:", input_json$`concreteType`))
        }
      } else {
        stop(paste("The JSON input `", input, "` is invalid for OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken: the required field `concreteType` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      # check if the required `concreteType` is null
      if (is.null(self$`concreteType`)) {
        return(FALSE)
      }

      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      # check if the required `concreteType` is null
      if (is.null(self$`concreteType`)) {
        invalid_fields["concreteType"] <- "Non-nullable required field `concreteType` cannot be null."
      }

      invalid_fields
    },
    #' Print the object
    #'
    #' @description
    #' Print the object
    #'
    #' @export
    print = function() {
      print(jsonlite::prettify(self$toJSONString()))
      invisible(self)
    }
  ),
  # Lock the class to prevent modifications to the method or field
  lock_class = TRUE
)
## Uncomment below to unlock the class to allow modifications of the method or field
# OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken$unlock()
#
## Below is an example to define the print function
# OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken$set("public", "print", function(...) {
#   print(jsonlite::prettify(self$toJSONString()))
#   invisible(self)
# })
## Uncomment below to lock the class to prevent modifications to the method or field
# OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken$lock()

